#!/bin/sh -e

if ! getent group openbook > /dev/null; then
    addgroup --system openbook
fi

if ! getent passwd openbook > /dev/null; then
    adduser --quiet \
        --system \
        --ingroup openbook \
        --quiet \
        --disabled-login \
        --disabled-password \
        --home /var/lib/openbook \
        -gecos "openbook" \
        openbook
fi
